### PR TITLE
add get transaction io endpoint

### PR DESCRIPTION
**Pull request by ozgrakkurt**

### CODE REVIEW

**Comment by ozgrakkurt** [comment]
Also have a question. How do we return errors from the api. I wanted to return a error if the transaction didn't exist.

Currently this endpoint returns an "empty" object like:
```js
{
  "inputs": [],
  "collateralInputs": [],
  "outputs": []
}
```

**Review by pedromtcosta — APPROVED** [review]
All good to me!

**Comment by ozgrakkurt** [comment]
@pedromtcosta I also parallelized the queries. I checked the order or `Promise.all` and it does return the promises in the order given to the function regardless of finishing order. [Promise.all#return_value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#return_value)

**Review by pedromtcosta — APPROVED** [review]

**Comment by vsubhuman** [comment]
@ozgrakkurt , plz resolve conflicts, plus see the change made by @pedromtcosta in this PR: https://github.com/Emurgo/yoroi-graphql-migration-backend/pull/277/files#diff-6cbd0e9e64bce1f6ff4ccd05ca2fb82187fb448eebd89eda83013b893a48fb46R128-R144

Maybe some of the created functions may be resued

**Comment by ozgrakkurt** [comment]
@vsubhuman resolved conflicts.

not possible to reuse them atm because they return json_agg but queries in io endpoint return normal sql rows.

**Review by vsubhuman — APPROVED** [review]

**Pull request merged**
