### PR TITLE
Add endpoint for NFT image validation

### PR DESCRIPTION
**Pull request by pedromtcosta**
Adds an endpoint for triggering [`Yoroi Content Validator`](https://github.com/Emurgo/yoroi-content-validator) for a given NFT fingerprint, or return the current validation results in case the validation was already performed

### NOTICE
for testing purposes this branch was rebased to [fix/change-endpoints-to-use-multi-asset-table](https://github.com/Emurgo/yoroi-graphql-migration-backend/tree/fix/change-endpoints-to-use-multi-asset-table) #284

### CODE REVIEW

**Comment by vsubhuman** [comment]
@pedromtcosta , resolve conflicts please

**Comment by pedromtcosta** [comment]
@vsubhuman conflicts resolved

**Comment by vsubhuman** [comment]
@pedromtcosta , resolve conflicts again please 😅

**Comment by pedromtcosta** [comment]
@vsubhuman this is a bit outdated now. I will change it to use the new Lambdas and resolve the conflicts in the process

**Comment by pedromtcosta** [comment]
@vsubhuman conflicts resolved. I also already updated the code to use the new Lambda

**Review by vsubhuman — APPROVED** [review]

**Pull request merged**
